import { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Privacy Policy — NutriTribe',
  description: 'Privacy Policy for NutriTribe — how we collect, use and protect your data.',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-ivory-grain pt-28 pb-20">
      <div className="max-w-3xl mx-auto px-6">
        <Link href="/" className="inline-flex items-center gap-2 font-body text-sm text-earthen-rust/50 hover:text-sun-harvest transition-colors mb-8">
          <ArrowLeft size={14} /> Back to Home
        </Link>

        <div className="mb-10">
          <p className="font-body text-xs font-semibold tracking-widest uppercase text-sun-harvest mb-3">Legal</p>
          <h1 className="font-display font-bold text-4xl text-earthen-rust mb-2">Privacy Policy</h1>
          <p className="font-body text-sm text-earthen-rust/45">Last updated: May 27, 2025</p>
        </div>

        <div className="prose-legal">
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>Words with capital letters have meanings defined under the following conditions. These definitions shall have the same meaning whether they appear in singular or plural.</p>

          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;) refers to Origins Tribes Private Limited, operating Nutri Tribe, KN-1266 RAMJEECHAK, DIGH Bataganj Dinapur-Cum-Khagaul, Patna, Bihar – 800018.</li>
            <li><strong>Cookies</strong> are small files placed on Your device by a website, containing details of Your browsing history among other uses.</li>
            <li><strong>Country</strong> refers to: Bihar, India.</li>
            <li><strong>Device</strong> means any device that can access the Service, such as a computer or a mobile phone.</li>
            <li><strong>Personal Data</strong> means any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website nutritribe.shop.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or legal entity on behalf of which such individual is using the Service.</li>
          </ul>

          <h2>Types of Data Collected</h2>
          <p>We may collect the following data:</p>
          <ul>
            <li>Personal identifiers: name, email, phone number, address, etc.</li>
            <li>Usage data: IP address, browser type, pages visited, device info, etc.</li>
          </ul>

          <h2>Use of Your Personal Data</h2>
          <p>We may use Personal Data for purposes including:</p>
          <ul>
            <li>To provide and maintain the Service</li>
            <li>To manage Your Account</li>
            <li>For contractual obligations</li>
            <li>To contact You with relevant communications</li>
            <li>To send You marketing and promotional offers</li>
            <li>For internal analysis and service improvement</li>
          </ul>

          <h2>Sharing Your Data</h2>
          <p>We may share Your data with:</p>
          <ul>
            <li>Service Providers</li>
            <li>Business Partners</li>
            <li>Affiliates</li>
            <li>Government authorities when required</li>
            <li>Other users with Your consent</li>
          </ul>

          <h2>Retention and Deletion</h2>
          <p>We retain Your Personal Data only as long as necessary. You can request deletion of Your data at any time by contacting us or through your account settings.</p>

          <h2>Security</h2>
          <p>We use commercially acceptable methods to protect Your data but cannot guarantee absolute security.</p>

          <h2>Children&apos;s Privacy</h2>
          <p>We do not knowingly collect data from individuals under the age of 13.</p>

          <h2>Third-Party Links</h2>
          <p>Our Service may contain links to third-party sites. We are not responsible for their content or privacy practices.</p>

          <h2>Changes to This Policy</h2>
          <p>We may update our Privacy Policy from time to time. Updates will be posted on this page and take effect immediately upon posting.</p>
        </div>

        <LegalNav current="privacy" />
      </div>
    </div>
  );
}

function LegalNav({ current }: { current: string }) {
  const links = [
    { href: '/terms-and-conditions', label: 'Terms & Conditions', key: 'terms' },
    { href: '/privacy-policy', label: 'Privacy Policy', key: 'privacy' },
    { href: '/shipping-policy', label: 'Shipping Policy', key: 'shipping' },
    { href: '/refund-policy', label: 'Refund Policy', key: 'refund' },
  ];
  return (
    <div className="mt-16 pt-8 border-t border-earthen-rust/10">
      <p className="font-body text-xs font-semibold tracking-widest uppercase text-earthen-rust/40 mb-4">Other Legal Pages</p>
      <div className="flex flex-wrap gap-3">
        {links.filter(l => l.key !== current).map(l => (
          <Link key={l.href} href={l.href}
            className="font-body text-xs font-semibold text-earthen-rust/60 hover:text-sun-harvest border border-earthen-rust/15 hover:border-sun-harvest/30 px-4 py-2 rounded-full transition-all">
            {l.label}
          </Link>
        ))}
      </div>
    </div>
  );
}
